# Generated by Django 5.2.1 on 2025-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grower',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='grower',
            name='business_name',
            field=models.CharField(default='Mango Growing Business', max_length=100),
        ),
    ]
